INSERT INTO salas (id_sala, nome_sala, descricao_sala, localizacao_sala) VALUES
(1, 'Sala01', '', NULL),
(2, 'Sala02', '', NULL),
(3, 'Sala03', '', NULL),
(4, 'Sala04', '', NULL),
(5, 'Sala05', '', NULL),
(6, 'Sala06', '', NULL),
(7, 'Sala07', '', NULL),
(8, 'Sala08', '', NULL),
(9, 'Sala09', '', NULL),
(10, 'Sala10', '', NULL),
(11, 'Sala11', '', NULL),
(12, 'Sala12', '', NULL),
(13, 'Sala13', '', NULL),
(14, 'Sala14', '', NULL),
(15, 'Sala15', '', NULL),
(16, 'LAB_DEV_SISTEMAS', '', NULL),
(17, 'LAB_INFORMATICA_I', '', NULL),
(18, 'LAB_INFORMATICA_II', '', NULL),
(19, 'LAB_ACIONAMENTOS', '', NULL),
(20, 'LAB_AUTOMACAO', '', NULL),
(21, 'LAB_MAKER', '', NULL),
(22, 'LAB_PNEUMATICA', '', NULL),
(23, 'LAB_QUIMICA_I', '', NULL),
(24, 'LAB_QUIMICA_II', '', NULL),
(25, 'LAB_LOGISTICA', '', NULL);
-- // Um Insert Das salas do Senai